env:
  exp_name: experiment_name
training:
  training_dir: /media/ADAS1/MARS/bbox_train/bbox_train/
  dataset: market1501
  batch_size: 128
  lr: 0.05
  criterion: triplet_cos
  triplet:
    margin: 1.0
  quadruplet:
    margin_alpha: 2.0
    margin_beta: 1.0
  kkt_weights: [1.0, 0.0]

validation:
  validation_dir: /media/ADAS1/MARS/bbox_test/bbox_test/
  batch_size: 256

testing:
  mot_testing_dir: /media/train_mot/
  batch_size: 256

metrics:
  # metric: tripletacc
  tripletacc:
    p: 2.0
  #  dist_thresh: 0.2
  # quadrupletacc:
  #   margin_alpha: 0.2
  #   margin_beta: 0.1

model:
  use_dropout: False
  act: relu
  blur: True
  arch_version: v0

trainer:
  logger: True
  checkpoint_callback: None
  enable_checkpointing: True
  callbacks: None
  default_root_dir: None
  gradient_clip_val: None
  gradient_clip_algorithm: None
  process_position: 0
  num_nodes: 1
  num_processes: None
  devices: None
  gpus: None
  auto_select_gpus: False
  tpu_cores: None
  ipus: None
  log_gpu_memory: None  # TODO: Remove in 1.7
  progress_bar_refresh_rate: None  # TODO: remove in v1.7
  enable_progress_bar: True
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: False
  accumulate_grad_batches: None
  max_epochs: None
  min_epochs: None
  max_steps: -1
  min_steps: None
  max_time: None
  limit_train_batches: None
  limit_val_batches: None
  limit_test_batches: None
  limit_predict_batches: None
  val_check_interval: None
  flush_logs_every_n_steps: None
  log_every_n_steps: 50
  accelerator: None
  strategy: None
  sync_batchnorm: False
  precision: 32
  enable_model_summary: True
  weights_summary: "top"
  weights_save_path: None  # TODO: Remove in 1.8
  num_sanity_val_steps: 2
  resume_from_checkpoint: None
  profiler: None
  benchmark: None
  deterministic: False
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: False
  replace_sampler_ddp: True
  detect_anomaly: False
  auto_scale_batch_size: False
  prepare_data_per_node: None
  plugins: None
  amp_backend: "native"
  amp_level: None
  move_metrics_to_cpu: False
  multiple_trainloader_mode: "max_size_cycle"
  stochastic_weight_avg: False
  terminate_on_nan: None