wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.6.15
    start_time: 1650560217
    t:
      1:
      - 1
      - 9
      - 41
      2:
      - 1
      - 9
      - 41
      3:
      - 7
      - 13
      4: 3.6.15
      5: 0.12.11
      8:
      - 5
config:
  desc: null
  value:
  - /home/cougarnet.uh.edu/eeplater/Documents/GitHub/improved_Deep_SORT/data/models/trial6/config.yaml
data:
  desc: null
  value:
    merge_from_dict: utils.YamlParser.merge_from_dict
    merge_from_file: utils.YamlParser.merge_from_file
    testing_dir: /media/ADAS1/MARS/bbox_test/bbox_test/
    training_dir: /home/cougarnet.uh.edu/eeplater/Documents/GitHub/improved_Deep_SORT/data/object-tracking-crops-data/crops
merge_from_dict:
  desc: null
  value: utils.YamlParser.merge_from_dict
merge_from_file:
  desc: null
  value: utils.YamlParser.merge_from_file
model:
  desc: null
  value:
    act: elu
    arch_version: v0
    blur: true
    merge_from_dict: utils.YamlParser.merge_from_dict
    merge_from_file: utils.YamlParser.merge_from_file
    use_dropout: false
trainer:
  desc: null
  value:
    accelerator: null
    accumulate_grad_batches: null
    amp_backend: native
    amp_level: null
    auto_lr_find: false
    auto_scale_batch_size: false
    auto_select_gpus: false
    benchmark: false
    callbacks: null
    check_val_every_n_epoch: 1
    checkpoint_callback: null
    default_root_dir: /home/cougarnet.uh.edu/eeplater/Documents/GitHub/improved_Deep_SORT/data/models/trial6
    detect_anomaly: false
    deterministic: false
    devices: null
    enable_checkpointing: true
    enable_model_summary: true
    enable_progress_bar: true
    fast_dev_run: false
    flush_logs_every_n_steps: null
    gpus: -1
    gradient_clip_algorithm: null
    gradient_clip_val: null
    ipus: null
    limit_predict_batches: 1.0
    limit_test_batches: 1.0
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    log_every_n_steps: 100
    log_gpu_memory: null
    logger: true
    max_epochs: 2
    max_steps: -1
    max_time: null
    merge_from_dict: utils.YamlParser.merge_from_dict
    merge_from_file: utils.YamlParser.merge_from_file
    min_epochs: null
    min_steps: null
    move_metrics_to_cpu: false
    multiple_trainloader_mode: max_size_cycle
    num_nodes: 1
    num_processes: 1
    num_sanity_val_steps: 2
    overfit_batches: 0.0
    plugins: null
    precision: 32
    prepare_data_per_node: null
    process_position: 0
    profiler: simple
    progress_bar_refresh_rate: null
    reload_dataloaders_every_epoch: false
    reload_dataloaders_every_n_epochs: 0
    replace_sampler_ddp: true
    resume_from_checkpoint: null
    stochastic_weight_avg: false
    strategy: null
    sync_batchnorm: false
    terminate_on_nan: null
    tpu_cores: null
    track_grad_norm: -1
    val_check_interval: 1.0
    weights_save_path: null
    weights_summary: top
training:
  desc: null
  value:
    batch_size: 128
    criterion: quad_learnedmetric
    lr: 0.0005
    merge_from_dict: utils.YamlParser.merge_from_dict
    merge_from_file: utils.YamlParser.merge_from_file
    quadruplet:
      margin_alpha: 0.1
      margin_beta: 0.01
      merge_from_dict: utils.YamlParser.merge_from_dict
      merge_from_file: utils.YamlParser.merge_from_file
    triplet:
      margin: 1.0
      merge_from_dict: utils.YamlParser.merge_from_dict
      merge_from_file: utils.YamlParser.merge_from_file
