wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.6.13
    start_time: 1648585663
    t:
      1:
      - 1
      - 9
      - 41
      2:
      - 1
      - 9
      - 41
      3:
      - 7
      - 13
      4: 3.6.13
      5: 0.12.11
      8:
      - 5
accelerator:
  desc: null
  value: null
accumulate_grad_batches:
  desc: null
  value: null
act:
  desc: null
  value: relu
amp_backend:
  desc: null
  value: native
amp_level:
  desc: null
  value: null
auto_lr_find:
  desc: null
  value: false
auto_scale_batch_size:
  desc: null
  value: false
auto_select_gpus:
  desc: null
  value: false
benchmark:
  desc: null
  value: false
callbacks:
  desc: null
  value: null
check_val_every_n_epoch:
  desc: null
  value: 1
checkpoint_callback:
  desc: null
  value: null
config:
  desc: null
  value:
  - /home/cougarnet.uh.edu/eeplater/Documents/GitHub/improved_Deep_SORT/data/models/config.yaml
default_root_dir:
  desc: null
  value: /home/cougarnet.uh.edu/eeplater/Documents/GitHub/improved_Deep_SORT/data/models
detect_anomaly:
  desc: null
  value: false
deterministic:
  desc: null
  value: false
devices:
  desc: null
  value: null
enable_checkpointing:
  desc: null
  value: true
enable_model_summary:
  desc: null
  value: true
enable_progress_bar:
  desc: null
  value: true
fast_dev_run:
  desc: null
  value: false
flush_logs_every_n_steps:
  desc: null
  value: null
gpus:
  desc: null
  value: -1
gradient_clip_algorithm:
  desc: null
  value: null
gradient_clip_val:
  desc: null
  value: null
ipus:
  desc: null
  value: null
limit_predict_batches:
  desc: null
  value: 1.0
limit_test_batches:
  desc: null
  value: 1.0
limit_train_batches:
  desc: null
  value: 1.0
limit_val_batches:
  desc: null
  value: 1.0
log_every_n_steps:
  desc: null
  value: 10
log_gpu_memory:
  desc: null
  value: null
logger:
  desc: null
  value: true
max_epoch:
  desc: null
  value: 5
max_epochs:
  desc: null
  value: null
max_steps:
  desc: null
  value: -1
max_time:
  desc: null
  value: null
min_epochs:
  desc: null
  value: null
min_steps:
  desc: null
  value: null
move_metrics_to_cpu:
  desc: null
  value: false
multiple_trainloader_mode:
  desc: null
  value: max_size_cycle
num_nodes:
  desc: null
  value: 1
num_processes:
  desc: null
  value: 1
num_sanity_val_steps:
  desc: null
  value: 2
overfit_batches:
  desc: null
  value: 0.0
plugins:
  desc: null
  value: null
precision:
  desc: null
  value: 32
prepare_data_per_node:
  desc: null
  value: null
process_position:
  desc: null
  value: 0
profiler:
  desc: null
  value: null
progress_bar_refresh_rate:
  desc: null
  value: null
reload_dataloaders_every_epoch:
  desc: null
  value: false
reload_dataloaders_every_n_epochs:
  desc: null
  value: 0
replace_sampler_ddp:
  desc: null
  value: true
resume_from_checkpoint:
  desc: null
  value: null
stochastic_weight_avg:
  desc: null
  value: false
strategy:
  desc: null
  value: null
sync_batchnorm:
  desc: null
  value: false
terminate_on_nan:
  desc: null
  value: null
testing_dir:
  desc: null
  value: /media/ADAS1/MARS/bbox_test/bbox_test/
tpu_cores:
  desc: null
  value: null
track_grad_norm:
  desc: null
  value: -1
train_batch_size:
  desc: null
  value: 128
trainer:
  desc: null
  value:
    accelerator: null
    accumulate_grad_batches: null
    amp_backend: native
    amp_level: null
    auto_lr_find: false
    auto_scale_batch_size: false
    auto_select_gpus: false
    benchmark: false
    callbacks: null
    check_val_every_n_epoch: 1
    checkpoint_callback: null
    default_root_dir: /home/cougarnet.uh.edu/eeplater/Documents/GitHub/improved_Deep_SORT/data/models
    detect_anomaly: false
    deterministic: false
    devices: null
    enable_checkpointing: true
    enable_model_summary: true
    enable_progress_bar: true
    fast_dev_run: false
    flush_logs_every_n_steps: null
    gpus: -1
    gradient_clip_algorithm: null
    gradient_clip_val: null
    ipus: null
    limit_predict_batches: 1.0
    limit_test_batches: 1.0
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    log_every_n_steps: 10
    log_gpu_memory: null
    logger: true
    max_epoch: 5
    max_epochs: null
    max_steps: -1
    max_time: null
    min_epochs: null
    min_steps: null
    move_metrics_to_cpu: false
    multiple_trainloader_mode: max_size_cycle
    num_nodes: 1
    num_processes: 1
    num_sanity_val_steps: 2
    overfit_batches: 0.0
    plugins: null
    precision: 32
    prepare_data_per_node: null
    process_position: 0
    profiler: null
    progress_bar_refresh_rate: null
    reload_dataloaders_every_epoch: false
    reload_dataloaders_every_n_epochs: 0
    replace_sampler_ddp: true
    resume_from_checkpoint: null
    stochastic_weight_avg: false
    strategy: null
    sync_batchnorm: false
    terminate_on_nan: null
    tpu_cores: null
    track_grad_norm: -1
    val_check_interval: 1.0
    weights_save_path: null
    weights_summary: top
training_dir:
  desc: null
  value: /home/cougarnet.uh.edu/eeplater/Documents/GitHub/improved_Deep_SORT/data/object-tracking-crops-data/crops
use_dropout:
  desc: null
  value: true
val_check_interval:
  desc: null
  value: 1.0
weights_save_path:
  desc: null
  value: null
weights_summary:
  desc: null
  value: top
