wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.6.15
    start_time: 1650244994
    t:
      1:
      - 1
      - 9
      - 41
      2:
      - 1
      - 9
      - 41
      3:
      - 7
      - 13
      4: 3.6.15
      5: 0.12.11
      8:
      - 5
config:
  desc: null
  value:
  - /home/cougarnet.uh.edu/eeplater/Documents/GitHub/improved_Deep_SORT/data/models/trial6/config.yaml
data:
  desc: null
  value: <__main__.Bunch object at 0x7f918dce9b38>
model:
  desc: null
  value: <__main__.Bunch object at 0x7f918dcf5940>
trainer:
  desc: null
  value: <__main__.Bunch object at 0x7f918dce9ef0>
training:
  desc: null
  value: <__main__.Bunch object at 0x7f918dce9fd0>
