wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.6.15
    start_time: 1649531006
    t:
      1:
      - 1
      - 9
      - 41
      2:
      - 1
      - 9
      - 41
      3:
      - 7
      - 13
      4: 3.6.15
      5: 0.12.11
      8:
      - 5
act:
  desc: null
  value: torch.nn.modules.activation.ReLU
arch_version:
  desc: null
  value: v3
blur:
  desc: null
  value: true
config:
  desc: null
  value:
  - /home/cougarnet.uh.edu/eeplater/Documents/GitHub/improved_Deep_SORT/data/models/trial5/config.yaml
criterion:
  desc: null
  value: TripletLoss()
lr:
  desc: null
  value: 0.005
testing_dir:
  desc: null
  value: /media/ADAS1/MARS/bbox_test/bbox_test/
train_batch_size:
  desc: null
  value: 128
trainer:
  desc: null
  value:
    accelerator: null
    accumulate_grad_batches: null
    amp_backend: native
    amp_level: null
    auto_lr_find: false
    auto_scale_batch_size: false
    auto_select_gpus: false
    benchmark: false
    callbacks: null
    check_val_every_n_epoch: 1
    checkpoint_callback: null
    default_root_dir: /home/cougarnet.uh.edu/eeplater/Documents/GitHub/improved_Deep_SORT/data/models/trial4
    detect_anomaly: false
    deterministic: false
    devices: null
    enable_checkpointing: true
    enable_model_summary: true
    enable_progress_bar: true
    fast_dev_run: false
    flush_logs_every_n_steps: null
    gpus: -1
    gradient_clip_algorithm: null
    gradient_clip_val: null
    ipus: null
    limit_predict_batches: 1.0
    limit_test_batches: 1.0
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    log_every_n_steps: 100
    log_gpu_memory: null
    logger: true
    max_epochs: 100
    max_steps: -1
    max_time: null
    min_epochs: null
    min_steps: null
    move_metrics_to_cpu: false
    multiple_trainloader_mode: max_size_cycle
    num_nodes: 1
    num_processes: 1
    num_sanity_val_steps: 2
    overfit_batches: 0.0
    plugins: null
    precision: 32
    prepare_data_per_node: null
    process_position: 0
    profiler: null
    progress_bar_refresh_rate: null
    reload_dataloaders_every_epoch: false
    reload_dataloaders_every_n_epochs: 0
    replace_sampler_ddp: true
    resume_from_checkpoint: null
    stochastic_weight_avg: false
    strategy: null
    sync_batchnorm: false
    terminate_on_nan: null
    tpu_cores: null
    track_grad_norm: -1
    val_check_interval: 1.0
    weights_save_path: null
    weights_summary: top
training_dir:
  desc: null
  value: /home/cougarnet.uh.edu/eeplater/Documents/GitHub/improved_Deep_SORT/data/object-tracking-crops-data/crops
use_dropout:
  desc: null
  value: false
