wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.15
    start_time: 1651697470
    t:
      1:
      - 1
      - 9
      - 41
      3:
      - 13
      4: 3.6.15
      5: 0.12.11
      8:
      - 5
